// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: frontend.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Application   *ApplicationSpec       `protobuf:"bytes,2,opt,name=application,proto3" json:"application,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterApplicationRequest) Reset() {
	*x = RegisterApplicationRequest{}
	mi := &file_frontend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterApplicationRequest) ProtoMessage() {}

func (x *RegisterApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterApplicationRequest.ProtoReflect.Descriptor instead.
func (*RegisterApplicationRequest) Descriptor() ([]byte, []int) {
	return file_frontend_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterApplicationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterApplicationRequest) GetApplication() *ApplicationSpec {
	if x != nil {
		return x.Application
	}
	return nil
}

type UnregisterApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterApplicationRequest) Reset() {
	*x = UnregisterApplicationRequest{}
	mi := &file_frontend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterApplicationRequest) ProtoMessage() {}

func (x *UnregisterApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterApplicationRequest.ProtoReflect.Descriptor instead.
func (*UnregisterApplicationRequest) Descriptor() ([]byte, []int) {
	return file_frontend_proto_rawDescGZIP(), []int{1}
}

func (x *UnregisterApplicationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Application   *ApplicationSpec       `protobuf:"bytes,2,opt,name=application,proto3" json:"application,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateApplicationRequest) Reset() {
	*x = UpdateApplicationRequest{}
	mi := &file_frontend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateApplicationRequest) ProtoMessage() {}

func (x *UpdateApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateApplicationRequest.ProtoReflect.Descriptor instead.
func (*UpdateApplicationRequest) Descriptor() ([]byte, []int) {
	return file_frontend_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateApplicationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateApplicationRequest) GetApplication() *ApplicationSpec {
	if x != nil {
		return x.Application
	}
	return nil
}

type GetApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplicationRequest) Reset() {
	*x = GetApplicationRequest{}
	mi := &file_frontend_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationRequest) ProtoMessage() {}

func (x *GetApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationRequest.ProtoReflect.Descriptor instead.
func (*GetApplicationRequest) Descriptor() ([]byte, []int) {
	return file_frontend_proto_rawDescGZIP(), []int{3}
}

func (x *GetApplicationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApplicationRequest) Reset() {
	*x = ListApplicationRequest{}
	mi := &file_frontend_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicationRequest) ProtoMessage() {}

func (x *ListApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicationRequest.ProtoReflect.Descriptor instead.
func (*ListApplicationRequest) Descriptor() ([]byte, []int) {
	return file_frontend_proto_rawDescGZIP(), []int{4}
}

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *SessionSpec           `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_frontend_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_frontend_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSessionRequest) GetSession() *SessionSpec {
	if x != nil {
		return x.Session
	}
	return nil
}

type DeleteSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_frontend_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_frontend_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type OpenSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenSessionRequest) Reset() {
	*x = OpenSessionRequest{}
	mi := &file_frontend_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSessionRequest) ProtoMessage() {}

func (x *OpenSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSessionRequest.ProtoReflect.Descriptor instead.
func (*OpenSessionRequest) Descriptor() ([]byte, []int) {
	return file_frontend_proto_rawDescGZIP(), []int{7}
}

func (x *OpenSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CloseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionRequest) Reset() {
	*x = CloseSessionRequest{}
	mi := &file_frontend_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionRequest) ProtoMessage() {}

func (x *CloseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionRequest.ProtoReflect.Descriptor instead.
func (*CloseSessionRequest) Descriptor() ([]byte, []int) {
	return file_frontend_proto_rawDescGZIP(), []int{8}
}

func (x *CloseSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_frontend_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_frontend_proto_rawDescGZIP(), []int{9}
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ListSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionRequest) Reset() {
	*x = ListSessionRequest{}
	mi := &file_frontend_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionRequest) ProtoMessage() {}

func (x *ListSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionRequest.ProtoReflect.Descriptor instead.
func (*ListSessionRequest) Descriptor() ([]byte, []int) {
	return file_frontend_proto_rawDescGZIP(), []int{10}
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *TaskSpec              `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_frontend_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_frontend_proto_rawDescGZIP(), []int{11}
}

func (x *CreateTaskRequest) GetTask() *TaskSpec {
	if x != nil {
		return x.Task
	}
	return nil
}

type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_frontend_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_frontend_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *DeleteTaskRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_frontend_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_frontend_proto_rawDescGZIP(), []int{13}
}

func (x *GetTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetTaskRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type WatchTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchTaskRequest) Reset() {
	*x = WatchTaskRequest{}
	mi := &file_frontend_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchTaskRequest) ProtoMessage() {}

func (x *WatchTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchTaskRequest.ProtoReflect.Descriptor instead.
func (*WatchTaskRequest) Descriptor() ([]byte, []int) {
	return file_frontend_proto_rawDescGZIP(), []int{14}
}

func (x *WatchTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *WatchTaskRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

var File_frontend_proto protoreflect.FileDescriptor

const file_frontend_proto_rawDesc = "" +
	"\n" +
	"\x0efrontend.proto\x12\x05flame\x1a\vtypes.proto\"j\n" +
	"\x1aRegisterApplicationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x128\n" +
	"\vapplication\x18\x02 \x01(\v2\x16.flame.ApplicationSpecR\vapplication\"2\n" +
	"\x1cUnregisterApplicationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"h\n" +
	"\x18UpdateApplicationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x128\n" +
	"\vapplication\x18\x02 \x01(\v2\x16.flame.ApplicationSpecR\vapplication\"+\n" +
	"\x15GetApplicationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x18\n" +
	"\x16ListApplicationRequest\"D\n" +
	"\x14CreateSessionRequest\x12,\n" +
	"\asession\x18\x01 \x01(\v2\x12.flame.SessionSpecR\asession\"5\n" +
	"\x14DeleteSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"3\n" +
	"\x12OpenSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"4\n" +
	"\x13CloseSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"2\n" +
	"\x11GetSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x14\n" +
	"\x12ListSessionRequest\"8\n" +
	"\x11CreateTaskRequest\x12#\n" +
	"\x04task\x18\x01 \x01(\v2\x0f.flame.TaskSpecR\x04task\"K\n" +
	"\x11DeleteTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"H\n" +
	"\x0eGetTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"J\n" +
	"\x10WatchTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId2\xc7\a\n" +
	"\bFrontend\x12I\n" +
	"\x13RegisterApplication\x12!.flame.RegisterApplicationRequest\x1a\r.flame.Result\"\x00\x12M\n" +
	"\x15UnregisterApplication\x12#.flame.UnregisterApplicationRequest\x1a\r.flame.Result\"\x00\x12E\n" +
	"\x11UpdateApplication\x12\x1f.flame.UpdateApplicationRequest\x1a\r.flame.Result\"\x00\x12D\n" +
	"\x0eGetApplication\x12\x1c.flame.GetApplicationRequest\x1a\x12.flame.Application\"\x00\x12J\n" +
	"\x0fListApplication\x12\x1d.flame.ListApplicationRequest\x1a\x16.flame.ApplicationList\"\x00\x12>\n" +
	"\rCreateSession\x12\x1b.flame.CreateSessionRequest\x1a\x0e.flame.Session\"\x00\x12>\n" +
	"\rDeleteSession\x12\x1b.flame.DeleteSessionRequest\x1a\x0e.flame.Session\"\x00\x12:\n" +
	"\vOpenSession\x12\x19.flame.OpenSessionRequest\x1a\x0e.flame.Session\"\x00\x12<\n" +
	"\fCloseSession\x12\x1a.flame.CloseSessionRequest\x1a\x0e.flame.Session\"\x00\x128\n" +
	"\n" +
	"GetSession\x12\x18.flame.GetSessionRequest\x1a\x0e.flame.Session\"\x00\x12>\n" +
	"\vListSession\x12\x19.flame.ListSessionRequest\x1a\x12.flame.SessionList\"\x00\x125\n" +
	"\n" +
	"CreateTask\x12\x18.flame.CreateTaskRequest\x1a\v.flame.Task\"\x00\x125\n" +
	"\n" +
	"DeleteTask\x12\x18.flame.DeleteTaskRequest\x1a\v.flame.Task\"\x00\x12/\n" +
	"\aGetTask\x12\x15.flame.GetTaskRequest\x1a\v.flame.Task\"\x00\x125\n" +
	"\tWatchTask\x12\x17.flame.WatchTaskRequest\x1a\v.flame.Task\"\x000\x01B&Z$github.com/flame-sh/flame/sdk/go/rpcb\x06proto3"

var (
	file_frontend_proto_rawDescOnce sync.Once
	file_frontend_proto_rawDescData []byte
)

func file_frontend_proto_rawDescGZIP() []byte {
	file_frontend_proto_rawDescOnce.Do(func() {
		file_frontend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_frontend_proto_rawDesc), len(file_frontend_proto_rawDesc)))
	})
	return file_frontend_proto_rawDescData
}

var file_frontend_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_frontend_proto_goTypes = []any{
	(*RegisterApplicationRequest)(nil),   // 0: flame.RegisterApplicationRequest
	(*UnregisterApplicationRequest)(nil), // 1: flame.UnregisterApplicationRequest
	(*UpdateApplicationRequest)(nil),     // 2: flame.UpdateApplicationRequest
	(*GetApplicationRequest)(nil),        // 3: flame.GetApplicationRequest
	(*ListApplicationRequest)(nil),       // 4: flame.ListApplicationRequest
	(*CreateSessionRequest)(nil),         // 5: flame.CreateSessionRequest
	(*DeleteSessionRequest)(nil),         // 6: flame.DeleteSessionRequest
	(*OpenSessionRequest)(nil),           // 7: flame.OpenSessionRequest
	(*CloseSessionRequest)(nil),          // 8: flame.CloseSessionRequest
	(*GetSessionRequest)(nil),            // 9: flame.GetSessionRequest
	(*ListSessionRequest)(nil),           // 10: flame.ListSessionRequest
	(*CreateTaskRequest)(nil),            // 11: flame.CreateTaskRequest
	(*DeleteTaskRequest)(nil),            // 12: flame.DeleteTaskRequest
	(*GetTaskRequest)(nil),               // 13: flame.GetTaskRequest
	(*WatchTaskRequest)(nil),             // 14: flame.WatchTaskRequest
	(*ApplicationSpec)(nil),              // 15: flame.ApplicationSpec
	(*SessionSpec)(nil),                  // 16: flame.SessionSpec
	(*TaskSpec)(nil),                     // 17: flame.TaskSpec
	(*Result)(nil),                       // 18: flame.Result
	(*Application)(nil),                  // 19: flame.Application
	(*ApplicationList)(nil),              // 20: flame.ApplicationList
	(*Session)(nil),                      // 21: flame.Session
	(*SessionList)(nil),                  // 22: flame.SessionList
	(*Task)(nil),                         // 23: flame.Task
}
var file_frontend_proto_depIdxs = []int32{
	15, // 0: flame.RegisterApplicationRequest.application:type_name -> flame.ApplicationSpec
	15, // 1: flame.UpdateApplicationRequest.application:type_name -> flame.ApplicationSpec
	16, // 2: flame.CreateSessionRequest.session:type_name -> flame.SessionSpec
	17, // 3: flame.CreateTaskRequest.task:type_name -> flame.TaskSpec
	0,  // 4: flame.Frontend.RegisterApplication:input_type -> flame.RegisterApplicationRequest
	1,  // 5: flame.Frontend.UnregisterApplication:input_type -> flame.UnregisterApplicationRequest
	2,  // 6: flame.Frontend.UpdateApplication:input_type -> flame.UpdateApplicationRequest
	3,  // 7: flame.Frontend.GetApplication:input_type -> flame.GetApplicationRequest
	4,  // 8: flame.Frontend.ListApplication:input_type -> flame.ListApplicationRequest
	5,  // 9: flame.Frontend.CreateSession:input_type -> flame.CreateSessionRequest
	6,  // 10: flame.Frontend.DeleteSession:input_type -> flame.DeleteSessionRequest
	7,  // 11: flame.Frontend.OpenSession:input_type -> flame.OpenSessionRequest
	8,  // 12: flame.Frontend.CloseSession:input_type -> flame.CloseSessionRequest
	9,  // 13: flame.Frontend.GetSession:input_type -> flame.GetSessionRequest
	10, // 14: flame.Frontend.ListSession:input_type -> flame.ListSessionRequest
	11, // 15: flame.Frontend.CreateTask:input_type -> flame.CreateTaskRequest
	12, // 16: flame.Frontend.DeleteTask:input_type -> flame.DeleteTaskRequest
	13, // 17: flame.Frontend.GetTask:input_type -> flame.GetTaskRequest
	14, // 18: flame.Frontend.WatchTask:input_type -> flame.WatchTaskRequest
	18, // 19: flame.Frontend.RegisterApplication:output_type -> flame.Result
	18, // 20: flame.Frontend.UnregisterApplication:output_type -> flame.Result
	18, // 21: flame.Frontend.UpdateApplication:output_type -> flame.Result
	19, // 22: flame.Frontend.GetApplication:output_type -> flame.Application
	20, // 23: flame.Frontend.ListApplication:output_type -> flame.ApplicationList
	21, // 24: flame.Frontend.CreateSession:output_type -> flame.Session
	21, // 25: flame.Frontend.DeleteSession:output_type -> flame.Session
	21, // 26: flame.Frontend.OpenSession:output_type -> flame.Session
	21, // 27: flame.Frontend.CloseSession:output_type -> flame.Session
	21, // 28: flame.Frontend.GetSession:output_type -> flame.Session
	22, // 29: flame.Frontend.ListSession:output_type -> flame.SessionList
	23, // 30: flame.Frontend.CreateTask:output_type -> flame.Task
	23, // 31: flame.Frontend.DeleteTask:output_type -> flame.Task
	23, // 32: flame.Frontend.GetTask:output_type -> flame.Task
	23, // 33: flame.Frontend.WatchTask:output_type -> flame.Task
	19, // [19:34] is the sub-list for method output_type
	4,  // [4:19] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_frontend_proto_init() }
func file_frontend_proto_init() {
	if File_frontend_proto != nil {
		return
	}
	file_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_frontend_proto_rawDesc), len(file_frontend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_frontend_proto_goTypes,
		DependencyIndexes: file_frontend_proto_depIdxs,
		MessageInfos:      file_frontend_proto_msgTypes,
	}.Build()
	File_frontend_proto = out.File
	file_frontend_proto_goTypes = nil
	file_frontend_proto_depIdxs = nil
}
