// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: shim.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplicationContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Shim          Shim                   `protobuf:"varint,2,opt,name=shim,proto3,enum=flame.Shim" json:"shim,omitempty"`
	Url           *string                `protobuf:"bytes,3,opt,name=url,proto3,oneof" json:"url,omitempty"`
	Command       *string                `protobuf:"bytes,4,opt,name=command,proto3,oneof" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationContext) Reset() {
	*x = ApplicationContext{}
	mi := &file_shim_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationContext) ProtoMessage() {}

func (x *ApplicationContext) ProtoReflect() protoreflect.Message {
	mi := &file_shim_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationContext.ProtoReflect.Descriptor instead.
func (*ApplicationContext) Descriptor() ([]byte, []int) {
	return file_shim_proto_rawDescGZIP(), []int{0}
}

func (x *ApplicationContext) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApplicationContext) GetShim() Shim {
	if x != nil {
		return x.Shim
	}
	return Shim_Log
}

func (x *ApplicationContext) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *ApplicationContext) GetCommand() string {
	if x != nil && x.Command != nil {
		return *x.Command
	}
	return ""
}

type SessionContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Application   *ApplicationContext    `protobuf:"bytes,2,opt,name=application,proto3" json:"application,omitempty"`
	CommonData    []byte                 `protobuf:"bytes,3,opt,name=common_data,json=commonData,proto3,oneof" json:"common_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionContext) Reset() {
	*x = SessionContext{}
	mi := &file_shim_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionContext) ProtoMessage() {}

func (x *SessionContext) ProtoReflect() protoreflect.Message {
	mi := &file_shim_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionContext.ProtoReflect.Descriptor instead.
func (*SessionContext) Descriptor() ([]byte, []int) {
	return file_shim_proto_rawDescGZIP(), []int{1}
}

func (x *SessionContext) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionContext) GetApplication() *ApplicationContext {
	if x != nil {
		return x.Application
	}
	return nil
}

func (x *SessionContext) GetCommonData() []byte {
	if x != nil {
		return x.CommonData
	}
	return nil
}

type TaskContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Input         []byte                 `protobuf:"bytes,4,opt,name=input,proto3,oneof" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskContext) Reset() {
	*x = TaskContext{}
	mi := &file_shim_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskContext) ProtoMessage() {}

func (x *TaskContext) ProtoReflect() protoreflect.Message {
	mi := &file_shim_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskContext.ProtoReflect.Descriptor instead.
func (*TaskContext) Descriptor() ([]byte, []int) {
	return file_shim_proto_rawDescGZIP(), []int{2}
}

func (x *TaskContext) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskContext) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TaskContext) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

type TaskOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3,oneof" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskOutput) Reset() {
	*x = TaskOutput{}
	mi := &file_shim_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskOutput) ProtoMessage() {}

func (x *TaskOutput) ProtoReflect() protoreflect.Message {
	mi := &file_shim_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskOutput.ProtoReflect.Descriptor instead.
func (*TaskOutput) Descriptor() ([]byte, []int) {
	return file_shim_proto_rawDescGZIP(), []int{3}
}

func (x *TaskOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RegisterServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	ServiceId     string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterServiceRequest) Reset() {
	*x = RegisterServiceRequest{}
	mi := &file_shim_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServiceRequest) ProtoMessage() {}

func (x *RegisterServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shim_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServiceRequest.ProtoReflect.Descriptor instead.
func (*RegisterServiceRequest) Descriptor() ([]byte, []int) {
	return file_shim_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterServiceRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterServiceRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type RegisterServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterServiceResponse) Reset() {
	*x = RegisterServiceResponse{}
	mi := &file_shim_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServiceResponse) ProtoMessage() {}

func (x *RegisterServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shim_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServiceResponse.ProtoReflect.Descriptor instead.
func (*RegisterServiceResponse) Descriptor() ([]byte, []int) {
	return file_shim_proto_rawDescGZIP(), []int{5}
}

var File_shim_proto protoreflect.FileDescriptor

const file_shim_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"shim.proto\x12\x05flame\x1a\vtypes.proto\"\x93\x01\n" +
	"\x12ApplicationContext\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\x04shim\x18\x02 \x01(\x0e2\v.flame.ShimR\x04shim\x12\x15\n" +
	"\x03url\x18\x03 \x01(\tH\x00R\x03url\x88\x01\x01\x12\x1d\n" +
	"\acommand\x18\x04 \x01(\tH\x01R\acommand\x88\x01\x01B\x06\n" +
	"\x04_urlB\n" +
	"\n" +
	"\b_command\"\xa2\x01\n" +
	"\x0eSessionContext\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12;\n" +
	"\vapplication\x18\x02 \x01(\v2\x19.flame.ApplicationContextR\vapplication\x12$\n" +
	"\vcommon_data\x18\x03 \x01(\fH\x00R\n" +
	"commonData\x88\x01\x01B\x0e\n" +
	"\f_common_data\"j\n" +
	"\vTaskContext\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x19\n" +
	"\x05input\x18\x04 \x01(\fH\x00R\x05input\x88\x01\x01B\b\n" +
	"\x06_input\".\n" +
	"\n" +
	"TaskOutput\x12\x17\n" +
	"\x04data\x18\x01 \x01(\fH\x00R\x04data\x88\x01\x01B\a\n" +
	"\x05_data\"Q\n" +
	"\x16RegisterServiceRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\"\x19\n" +
	"\x17RegisterServiceResponse2\xb5\x01\n" +
	"\bGrpcShim\x128\n" +
	"\x0eOnSessionEnter\x12\x15.flame.SessionContext\x1a\r.flame.Result\"\x00\x127\n" +
	"\fOnTaskInvoke\x12\x12.flame.TaskContext\x1a\x11.flame.TaskOutput\"\x00\x126\n" +
	"\x0eOnSessionLeave\x12\x13.flame.EmptyRequest\x1a\r.flame.Result\"\x002h\n" +
	"\x12GrpcServiceManager\x12R\n" +
	"\x0fRegisterService\x12\x1d.flame.RegisterServiceRequest\x1a\x1e.flame.RegisterServiceResponse\"\x00B&Z$github.com/flame-sh/flame/sdk/go/rpcb\x06proto3"

var (
	file_shim_proto_rawDescOnce sync.Once
	file_shim_proto_rawDescData []byte
)

func file_shim_proto_rawDescGZIP() []byte {
	file_shim_proto_rawDescOnce.Do(func() {
		file_shim_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shim_proto_rawDesc), len(file_shim_proto_rawDesc)))
	})
	return file_shim_proto_rawDescData
}

var file_shim_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_shim_proto_goTypes = []any{
	(*ApplicationContext)(nil),      // 0: flame.ApplicationContext
	(*SessionContext)(nil),          // 1: flame.SessionContext
	(*TaskContext)(nil),             // 2: flame.TaskContext
	(*TaskOutput)(nil),              // 3: flame.TaskOutput
	(*RegisterServiceRequest)(nil),  // 4: flame.RegisterServiceRequest
	(*RegisterServiceResponse)(nil), // 5: flame.RegisterServiceResponse
	(Shim)(0),                       // 6: flame.Shim
	(*EmptyRequest)(nil),            // 7: flame.EmptyRequest
	(*Result)(nil),                  // 8: flame.Result
}
var file_shim_proto_depIdxs = []int32{
	6, // 0: flame.ApplicationContext.shim:type_name -> flame.Shim
	0, // 1: flame.SessionContext.application:type_name -> flame.ApplicationContext
	1, // 2: flame.GrpcShim.OnSessionEnter:input_type -> flame.SessionContext
	2, // 3: flame.GrpcShim.OnTaskInvoke:input_type -> flame.TaskContext
	7, // 4: flame.GrpcShim.OnSessionLeave:input_type -> flame.EmptyRequest
	4, // 5: flame.GrpcServiceManager.RegisterService:input_type -> flame.RegisterServiceRequest
	8, // 6: flame.GrpcShim.OnSessionEnter:output_type -> flame.Result
	3, // 7: flame.GrpcShim.OnTaskInvoke:output_type -> flame.TaskOutput
	8, // 8: flame.GrpcShim.OnSessionLeave:output_type -> flame.Result
	5, // 9: flame.GrpcServiceManager.RegisterService:output_type -> flame.RegisterServiceResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_shim_proto_init() }
func file_shim_proto_init() {
	if File_shim_proto != nil {
		return
	}
	file_types_proto_init()
	file_shim_proto_msgTypes[0].OneofWrappers = []any{}
	file_shim_proto_msgTypes[1].OneofWrappers = []any{}
	file_shim_proto_msgTypes[2].OneofWrappers = []any{}
	file_shim_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shim_proto_rawDesc), len(file_shim_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_shim_proto_goTypes,
		DependencyIndexes: file_shim_proto_depIdxs,
		MessageInfos:      file_shim_proto_msgTypes,
	}.Build()
	File_shim_proto = out.File
	file_shim_proto_goTypes = nil
	file_shim_proto_depIdxs = nil
}
