// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: shim.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplicationContext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Shim    Shim    `protobuf:"varint,2,opt,name=shim,proto3,enum=flame.Shim" json:"shim,omitempty"`
	Image   *string `protobuf:"bytes,3,opt,name=image,proto3,oneof" json:"image,omitempty"`
	Command *string `protobuf:"bytes,4,opt,name=command,proto3,oneof" json:"command,omitempty"`
}

func (x *ApplicationContext) Reset() {
	*x = ApplicationContext{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shim_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplicationContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationContext) ProtoMessage() {}

func (x *ApplicationContext) ProtoReflect() protoreflect.Message {
	mi := &file_shim_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationContext.ProtoReflect.Descriptor instead.
func (*ApplicationContext) Descriptor() ([]byte, []int) {
	return file_shim_proto_rawDescGZIP(), []int{0}
}

func (x *ApplicationContext) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApplicationContext) GetShim() Shim {
	if x != nil {
		return x.Shim
	}
	return Shim_Log
}

func (x *ApplicationContext) GetImage() string {
	if x != nil && x.Image != nil {
		return *x.Image
	}
	return ""
}

func (x *ApplicationContext) GetCommand() string {
	if x != nil && x.Command != nil {
		return *x.Command
	}
	return ""
}

type SessionContext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId   string              `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Application *ApplicationContext `protobuf:"bytes,2,opt,name=application,proto3" json:"application,omitempty"`
	CommonData  []byte              `protobuf:"bytes,3,opt,name=common_data,json=commonData,proto3,oneof" json:"common_data,omitempty"`
}

func (x *SessionContext) Reset() {
	*x = SessionContext{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shim_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionContext) ProtoMessage() {}

func (x *SessionContext) ProtoReflect() protoreflect.Message {
	mi := &file_shim_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionContext.ProtoReflect.Descriptor instead.
func (*SessionContext) Descriptor() ([]byte, []int) {
	return file_shim_proto_rawDescGZIP(), []int{1}
}

func (x *SessionContext) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionContext) GetApplication() *ApplicationContext {
	if x != nil {
		return x.Application
	}
	return nil
}

func (x *SessionContext) GetCommonData() []byte {
	if x != nil {
		return x.CommonData
	}
	return nil
}

type TaskContext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId    string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Input     []byte `protobuf:"bytes,4,opt,name=input,proto3,oneof" json:"input,omitempty"`
}

func (x *TaskContext) Reset() {
	*x = TaskContext{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shim_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskContext) ProtoMessage() {}

func (x *TaskContext) ProtoReflect() protoreflect.Message {
	mi := &file_shim_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskContext.ProtoReflect.Descriptor instead.
func (*TaskContext) Descriptor() ([]byte, []int) {
	return file_shim_proto_rawDescGZIP(), []int{2}
}

func (x *TaskContext) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskContext) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TaskContext) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

type TaskOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3,oneof" json:"data,omitempty"`
}

func (x *TaskOutput) Reset() {
	*x = TaskOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shim_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskOutput) ProtoMessage() {}

func (x *TaskOutput) ProtoReflect() protoreflect.Message {
	mi := &file_shim_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskOutput.ProtoReflect.Descriptor instead.
func (*TaskOutput) Descriptor() ([]byte, []int) {
	return file_shim_proto_rawDescGZIP(), []int{3}
}

func (x *TaskOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_shim_proto protoreflect.FileDescriptor

var file_shim_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x73, 0x68, 0x69, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x66, 0x6c,
	0x61, 0x6d, 0x65, 0x1a, 0x0b, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x99, 0x01, 0x0a, 0x12, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x73,
	0x68, 0x69, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x66, 0x6c, 0x61, 0x6d,
	0x65, 0x2e, 0x53, 0x68, 0x69, 0x6d, 0x52, 0x04, 0x73, 0x68, 0x69, 0x6d, 0x12, 0x19, 0x0a, 0x05,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0xa2, 0x01, 0x0a,
	0x0e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x3b,
	0x0a, 0x0b, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x66, 0x6c, 0x61, 0x6d, 0x65, 0x2e, 0x41, 0x70, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x0b,
	0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0b, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x48, 0x00, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x88, 0x01,
	0x01, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x6a, 0x0a, 0x0b, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74,
	0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x22, 0x2e, 0x0a,
	0x0a, 0x54, 0x61, 0x73, 0x6b, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x17, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x32, 0xb5, 0x01,
	0x0a, 0x08, 0x47, 0x72, 0x70, 0x63, 0x53, 0x68, 0x69, 0x6d, 0x12, 0x38, 0x0a, 0x0e, 0x4f, 0x6e,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x15, 0x2e, 0x66,
	0x6c, 0x61, 0x6d, 0x65, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x78, 0x74, 0x1a, 0x0d, 0x2e, 0x66, 0x6c, 0x61, 0x6d, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x0c, 0x4f, 0x6e, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e,
	0x76, 0x6f, 0x6b, 0x65, 0x12, 0x12, 0x2e, 0x66, 0x6c, 0x61, 0x6d, 0x65, 0x2e, 0x54, 0x61, 0x73,
	0x6b, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x1a, 0x11, 0x2e, 0x66, 0x6c, 0x61, 0x6d, 0x65,
	0x2e, 0x54, 0x61, 0x73, 0x6b, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x00, 0x12, 0x36, 0x0a,
	0x0e, 0x4f, 0x6e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x12,
	0x13, 0x2e, 0x66, 0x6c, 0x61, 0x6d, 0x65, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x66, 0x6c, 0x61, 0x6d, 0x65, 0x2e, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x22, 0x00, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x6c, 0x61, 0x6d, 0x65, 0x2d, 0x73, 0x68, 0x2f, 0x66, 0x6c, 0x61,
	0x6d, 0x65, 0x2f, 0x73, 0x64, 0x6b, 0x2f, 0x67, 0x6f, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shim_proto_rawDescOnce sync.Once
	file_shim_proto_rawDescData = file_shim_proto_rawDesc
)

func file_shim_proto_rawDescGZIP() []byte {
	file_shim_proto_rawDescOnce.Do(func() {
		file_shim_proto_rawDescData = protoimpl.X.CompressGZIP(file_shim_proto_rawDescData)
	})
	return file_shim_proto_rawDescData
}

var file_shim_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_shim_proto_goTypes = []interface{}{
	(*ApplicationContext)(nil), // 0: flame.ApplicationContext
	(*SessionContext)(nil),     // 1: flame.SessionContext
	(*TaskContext)(nil),        // 2: flame.TaskContext
	(*TaskOutput)(nil),         // 3: flame.TaskOutput
	(Shim)(0),                  // 4: flame.Shim
	(*EmptyRequest)(nil),       // 5: flame.EmptyRequest
	(*Result)(nil),             // 6: flame.Result
}
var file_shim_proto_depIdxs = []int32{
	4, // 0: flame.ApplicationContext.shim:type_name -> flame.Shim
	0, // 1: flame.SessionContext.application:type_name -> flame.ApplicationContext
	1, // 2: flame.GrpcShim.OnSessionEnter:input_type -> flame.SessionContext
	2, // 3: flame.GrpcShim.OnTaskInvoke:input_type -> flame.TaskContext
	5, // 4: flame.GrpcShim.OnSessionLeave:input_type -> flame.EmptyRequest
	6, // 5: flame.GrpcShim.OnSessionEnter:output_type -> flame.Result
	3, // 6: flame.GrpcShim.OnTaskInvoke:output_type -> flame.TaskOutput
	6, // 7: flame.GrpcShim.OnSessionLeave:output_type -> flame.Result
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_shim_proto_init() }
func file_shim_proto_init() {
	if File_shim_proto != nil {
		return
	}
	file_types_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_shim_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplicationContext); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shim_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionContext); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shim_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskContext); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shim_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_shim_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_shim_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_shim_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_shim_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shim_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shim_proto_goTypes,
		DependencyIndexes: file_shim_proto_depIdxs,
		MessageInfos:      file_shim_proto_msgTypes,
	}.Build()
	File_shim_proto = out.File
	file_shim_proto_rawDesc = nil
	file_shim_proto_goTypes = nil
	file_shim_proto_depIdxs = nil
}
