# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shim.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'shim.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import types_pb2 as types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nshim.proto\x12\x05\x66lame\x1a\x0btypes.proto\"y\n\x12\x41pplicationContext\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x19\n\x04shim\x18\x02 \x01(\x0e\x32\x0b.flame.Shim\x12\x10\n\x03url\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x07\x63ommand\x18\x04 \x01(\tH\x01\x88\x01\x01\x42\x06\n\x04_urlB\n\n\x08_command\"~\n\x0eSessionContext\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12.\n\x0b\x61pplication\x18\x02 \x01(\x0b\x32\x19.flame.ApplicationContext\x12\x18\n\x0b\x63ommon_data\x18\x03 \x01(\x0cH\x00\x88\x01\x01\x42\x0e\n\x0c_common_data\"P\n\x0bTaskContext\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x12\n\x05input\x18\x04 \x01(\x0cH\x00\x88\x01\x01\x42\x08\n\x06_input\"(\n\nTaskOutput\x12\x11\n\x04\x64\x61ta\x18\x01 \x01(\x0cH\x00\x88\x01\x01\x42\x07\n\x05_data\"=\n\x16RegisterServiceRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x12\n\nservice_id\x18\x02 \x01(\t\"\x19\n\x17RegisterServiceResponse2\xb5\x01\n\x08GrpcShim\x12\x38\n\x0eOnSessionEnter\x12\x15.flame.SessionContext\x1a\r.flame.Result\"\x00\x12\x37\n\x0cOnTaskInvoke\x12\x12.flame.TaskContext\x1a\x11.flame.TaskOutput\"\x00\x12\x36\n\x0eOnSessionLeave\x12\x13.flame.EmptyRequest\x1a\r.flame.Result\"\x00\x32h\n\x12GrpcServiceManager\x12R\n\x0fRegisterService\x12\x1d.flame.RegisterServiceRequest\x1a\x1e.flame.RegisterServiceResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shim_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APPLICATIONCONTEXT']._serialized_start=34
  _globals['_APPLICATIONCONTEXT']._serialized_end=155
  _globals['_SESSIONCONTEXT']._serialized_start=157
  _globals['_SESSIONCONTEXT']._serialized_end=283
  _globals['_TASKCONTEXT']._serialized_start=285
  _globals['_TASKCONTEXT']._serialized_end=365
  _globals['_TASKOUTPUT']._serialized_start=367
  _globals['_TASKOUTPUT']._serialized_end=407
  _globals['_REGISTERSERVICEREQUEST']._serialized_start=409
  _globals['_REGISTERSERVICEREQUEST']._serialized_end=470
  _globals['_REGISTERSERVICERESPONSE']._serialized_start=472
  _globals['_REGISTERSERVICERESPONSE']._serialized_end=497
  _globals['_GRPCSHIM']._serialized_start=500
  _globals['_GRPCSHIM']._serialized_end=681
  _globals['_GRPCSERVICEMANAGER']._serialized_start=683
  _globals['_GRPCSERVICEMANAGER']._serialized_end=787
# @@protoc_insertion_point(module_scope)
