FROM rust:1.82-slim-bookworm as builder

WORKDIR /usr/src/flame
COPY . .
RUN apt-get update && apt-get install -y protobuf-compiler pkg-config libssl-dev
RUN cargo install --path ./flmctl
RUN cargo install --path ./flmping

FROM ubuntu:22.04
RUN apt-get update && apt-get install -y wget vim iputils-ping ssh
COPY --from=builder /usr/local/cargo/bin/flmping /usr/local/bin/flmping
COPY --from=builder /usr/local/cargo/bin/flmctl /usr/local/bin/flmctl

CMD ["service", "ssh", "start", "-D"]
