[package]
name = "flmexec"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flame-rs = { path = "../sdk/rust" }

tokio = { workspace = true }
tonic = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_derive = { workspace = true }
futures = "0.3"
clap = { version = "4.1", features = ["derive"] }
chrono = "0.4"
indicatif = {version = "*", features = ["rayon"]}
tempfile = {version = "*"}
rand = { workspace = true }

[[bin]]
name = "flmexec"
path = "src/client.rs"

[[bin]]
name = "flmexec-service"
path = "src/service.rs"
