# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frontend.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import types_pb2 as types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x66rontend.proto\x12\x05\x66lame\x1a\x0btypes.proto\";\n\x14\x43reateSessionRequest\x12#\n\x07session\x18\x01 \x01(\x0b\x32\x12.flame.SessionSpec\"*\n\x14\x44\x65leteSessionRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"(\n\x12OpenSessionRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\")\n\x13\x43loseSessionRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"\'\n\x11GetSessionRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"\x14\n\x12ListSessionRequest\"2\n\x11\x43reateTaskRequest\x12\x1d\n\x04task\x18\x01 \x01(\x0b\x32\x0f.flame.TaskSpec\"8\n\x11\x44\x65leteTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\"5\n\x0eGetTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\"7\n\x10WatchTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t2\xd4\x04\n\x08\x46rontend\x12>\n\rCreateSession\x12\x1b.flame.CreateSessionRequest\x1a\x0e.flame.Session\"\x00\x12>\n\rDeleteSession\x12\x1b.flame.DeleteSessionRequest\x1a\x0e.flame.Session\"\x00\x12:\n\x0bOpenSession\x12\x19.flame.OpenSessionRequest\x1a\x0e.flame.Session\"\x00\x12<\n\x0c\x43loseSession\x12\x1a.flame.CloseSessionRequest\x1a\x0e.flame.Session\"\x00\x12\x38\n\nGetSession\x12\x18.flame.GetSessionRequest\x1a\x0e.flame.Session\"\x00\x12>\n\x0bListSession\x12\x19.flame.ListSessionRequest\x1a\x12.flame.SessionList\"\x00\x12\x35\n\nCreateTask\x12\x18.flame.CreateTaskRequest\x1a\x0b.flame.Task\"\x00\x12\x35\n\nDeleteTask\x12\x18.flame.DeleteTaskRequest\x1a\x0b.flame.Task\"\x00\x12/\n\x07GetTask\x12\x15.flame.GetTaskRequest\x1a\x0b.flame.Task\"\x00\x12\x35\n\tWatchTask\x12\x17.flame.WatchTaskRequest\x1a\x0b.flame.Task\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'frontend_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CREATESESSIONREQUEST']._serialized_start=38
  _globals['_CREATESESSIONREQUEST']._serialized_end=97
  _globals['_DELETESESSIONREQUEST']._serialized_start=99
  _globals['_DELETESESSIONREQUEST']._serialized_end=141
  _globals['_OPENSESSIONREQUEST']._serialized_start=143
  _globals['_OPENSESSIONREQUEST']._serialized_end=183
  _globals['_CLOSESESSIONREQUEST']._serialized_start=185
  _globals['_CLOSESESSIONREQUEST']._serialized_end=226
  _globals['_GETSESSIONREQUEST']._serialized_start=228
  _globals['_GETSESSIONREQUEST']._serialized_end=267
  _globals['_LISTSESSIONREQUEST']._serialized_start=269
  _globals['_LISTSESSIONREQUEST']._serialized_end=289
  _globals['_CREATETASKREQUEST']._serialized_start=291
  _globals['_CREATETASKREQUEST']._serialized_end=341
  _globals['_DELETETASKREQUEST']._serialized_start=343
  _globals['_DELETETASKREQUEST']._serialized_end=399
  _globals['_GETTASKREQUEST']._serialized_start=401
  _globals['_GETTASKREQUEST']._serialized_end=454
  _globals['_WATCHTASKREQUEST']._serialized_start=456
  _globals['_WATCHTASKREQUEST']._serialized_end=511
  _globals['_FRONTEND']._serialized_start=514
  _globals['_FRONTEND']._serialized_end=1110
# @@protoc_insertion_point(module_scope)
