name: Flame CI
on: [push, pull_request]
env:
  CLICOLOR_FORCE: 1
jobs:
  ci:
    name: Code Verify
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        rust: [stable]
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.x
          cache: true
      - name: Install Go dependencies
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.30.0
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.3.0
      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --debug cargo-make
      - name: Install gRPC
        run: |
          sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - name: Cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: check-format-ci-flow
      - name: Cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: clippy-ci-flow
      - name: Cargo make
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: build-release
      - name: Go lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.55.2
          args: --fix
          working-directory: sdk/go