name: Flame CI
on: [push, pull_request]
env:
  CLICOLOR_FORCE: 1
jobs:
  ci:
    name: Code Verify
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        rust: [stable]
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --debug cargo-make
      - name: Install gRPC
        run: |
          sudo apt-get update && sudo apt-get install -y protobuf-compiler
       - name: Cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: check-format-ci-flow
      - name: Cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: clippy-ci-flow
      - name: Cargo make
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: build-release
