name: Flame CI
on: [push, pull_request]
env:
  CLICOLOR_FORCE: 1
jobs:
  ci:
    name: Rust E2E Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        rust: [stable]
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Start Flame
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./compose.yaml"
      - name: Install gRPC
        run: |
          sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
      - name: Run Rust E2E Test
        run: |
          cargo test -- --nocapture

