name: Flame CI
on: [push, pull_request]
env:
  CLICOLOR_FORCE: 1
jobs:
  ci:
    name: Python E2E Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        rust: [stable]
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Start Flame
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./compose.yaml"
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Run Python E2E Test
        run: |
          make sdk-python-test