apiVersion: apps/v1
kind: Deployment
metadata:
  name: flame-console
  labels:
    app.kubernetes.io/name: flame-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: flame-console
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flame-console
    spec:
      containers:
      - name: console
        image: registry.minikube/flame-console:latest
        env:
        - name: RUST_LOG
          value: "info"
        volumeMounts:
        - name: flame-conf
          mountPath: /root/.flame
      volumes:
      - name: flame-conf
        configMap:
          name: flame-conf